version: '3.8'
   services:
  postgres_db:
  image: postgres:latest
  container_name: PostgresCont 
  restart: always
  environment:
  - POSTGRES_USER=tolga.erdogan
  - POSTGRES_PASSWORD=***Kuzey06...
  ports:
  - '5432:5432'
  volumes:
  - postgres_db:/var/lib/postgresql/data
   volumes:
  postgres_db:
  driver: local